name: flutter_convex
description: A Flutter package for Convex integration with real-time subscriptions and optimistic updates.
version: 0.1.0
repository: https://github.com/quilldevtools/flutter_convex
issue_tracker: https://github.com/quilldevtools/flutter_convex/issues
documentation: https://github.com/quilldevtools/flutter_convex#readme

environment:
  sdk: ^3.7.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
